/**
 * Types and URL sequence generation helpers for the BatchDownloadModal.
 */
import { Category } from '../../../types/download';

export type BatchTab = 'pattern' | 'text' | 'crawler';

export interface ScrapedLink {
  filename: string;
  url: string;
  subfolder?: string;
  size?: number;
  size_str?: string;
  ext?: string;
  category?: string;
  selected?: boolean;
}

export interface WildcardConfig {
  seqType: 'numeric' | 'alpha';
  numFrom: string | number;
  numTo: string | number;
  numStep: number;
  alphaFrom: string;
  alphaTo: string;
  alphaStep: number;
}

export interface BatchSubmitProgress {
  current: number;
  total: number;
  percent: number;
  currentName: string;
}

export interface ActiveBatchItem {
  url: string;
  filename: string;
  subfolder?: string;
  category?: Category;
}

export const DEFAULT_WILDCARD_CONFIG: WildcardConfig = {
  seqType: 'numeric',
  numFrom: '1',
  numTo: '10',
  numStep: 1,
  alphaFrom: 'a',
  alphaTo: 'j',
  alphaStep: 1,
};

/**
 * Formats byte counts into human-readable strings for the batch link table.
 */
export const formatBatchBytes = (bytes?: number): string => {
  if (!bytes || bytes <= 0) return 'Unknown';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
};

/**
 * Computes up to 6 preview values for a given wildcard configuration.
 */
export const computeWildcardSampleValues = (currentConfig: WildcardConfig): string[] => {
  const vals: string[] = [];
  if (currentConfig.seqType === 'numeric') {
    const fromStr = String(currentConfig.numFrom ?? '1').trim();
    const toStr = String(currentConfig.numTo ?? '10').trim();
    const from = parseInt(fromStr, 10) || 0;
    const to = parseInt(toStr, 10) || 0;
    const step = Math.max(1, Math.abs(currentConfig.numStep || 1));
    const padLen =
      fromStr.startsWith('0') && fromStr.length > 1
        ? fromStr.length
        : toStr.startsWith('0') && toStr.length > 1
        ? toStr.length
        : 0;

    if (from <= to) {
      for (let v = from; v <= to && vals.length < 6; v += step) {
        vals.push(padLen > 0 ? String(v).padStart(padLen, '0') : String(v));
      }
    } else {
      for (let v = from; v >= to && vals.length < 6; v -= step) {
        vals.push(padLen > 0 ? String(v).padStart(padLen, '0') : String(v));
      }
    }
  } else {
    const fromRaw = (currentConfig.alphaFrom || '').trim();
    const toRaw = (currentConfig.alphaTo || '').trim();
    const fromChar = fromRaw ? fromRaw[0] : 'a';
    const toChar = toRaw ? toRaw[0] : fromChar >= 'A' && fromChar <= 'Z' ? 'Z' : 'z';
    const startCode = fromChar.charCodeAt(0);
    const endCode = toChar.charCodeAt(0);
    const step = Math.max(1, Math.abs(currentConfig.alphaStep || 1));

    if (startCode <= endCode) {
      for (let c = startCode; c <= endCode && vals.length < 6; c += step) {
        vals.push(String.fromCharCode(c));
      }
    } else {
      for (let c = startCode; c >= endCode && vals.length < 6; c -= step) {
        vals.push(String.fromCharCode(c));
      }
    }
  }
  return vals;
};

/**
 * Computes the total number of items generated by a single wildcard configuration.
 */
export const computeWildcardSampleTotal = (currentConfig: WildcardConfig): number => {
  if (currentConfig.seqType === 'numeric') {
    const fromStr = String(currentConfig.numFrom ?? '1').trim();
    const toStr = String(currentConfig.numTo ?? '10').trim();
    const from = parseInt(fromStr, 10) || 0;
    const to = parseInt(toStr, 10) || 0;
    const diff = Math.abs(to - from);
    const step = Math.max(1, Math.abs(currentConfig.numStep || 1));
    return Math.floor(diff / step) + 1;
  } else {
    const fromRaw = (currentConfig.alphaFrom || '').trim();
    const toRaw = (currentConfig.alphaTo || '').trim();
    const fromChar = fromRaw ? fromRaw[0] : 'a';
    const toChar = toRaw ? toRaw[0] : fromChar >= 'A' && fromChar <= 'Z' ? 'Z' : 'z';
    const startCode = fromChar.charCodeAt(0);
    const endCode = toChar.charCodeAt(0);
    const diff = Math.abs(endCode - startCode);
    const step = Math.max(1, Math.abs(currentConfig.alphaStep || 1));
    return Math.floor(diff / step) + 1;
  }
};

/**
 * Expands a URL template containing bracket ranges ([01-20:2], [a-z]) and asterisks (*)
 * into up to 2,000 concrete URLs.
 */
export const generatePatternUrls = (
  patternUrl: string,
  wildcardConfigs: WildcardConfig[]
): string[] => {
  const rawTemplate = patternUrl.trim();
  if (!rawTemplate) return [];

  let templateWithTokens = rawTemplate;
  const tokens: string[] = [];
  const varValueSets: string[][] = [];

  // 1. Check for bracket ranges: [01-20], [01-20:2], [a-z], [a-z:2]
  const bracketRegex = /\[(?:([0-9]+)-([0-9]+)(?::([0-9]+))?|([a-zA-Z])-([a-zA-Z])(?::([0-9]+))?)\]/g;
  let bMatch: RegExpExecArray | null;
  let bracketIndex = 0;

  const bracketMatches: Array<{ matchStr: string; values: string[] }> = [];
  while ((bMatch = bracketRegex.exec(rawTemplate)) !== null) {
    const matchStr = bMatch[0];
    const vals: string[] = [];
    if (bMatch[1] !== undefined && bMatch[2] !== undefined) {
      // Numeric bracket
      const start = parseInt(bMatch[1], 10);
      const end = parseInt(bMatch[2], 10);
      const step = bMatch[3] ? Math.max(1, parseInt(bMatch[3], 10)) : 1;
      const padLen = bMatch[1].length;
      if (start <= end) {
        for (let v = start; v <= end && vals.length < 1000; v += step) {
          vals.push(String(v).padStart(padLen, '0'));
        }
      } else {
        for (let v = start; v >= end && vals.length < 1000; v -= step) {
          vals.push(String(v).padStart(padLen, '0'));
        }
      }
    } else if (bMatch[4] !== undefined && bMatch[5] !== undefined) {
      // Alpha bracket
      const startCode = bMatch[4].charCodeAt(0);
      const endCode = bMatch[5].charCodeAt(0);
      const step = bMatch[6] ? Math.max(1, parseInt(bMatch[6], 10)) : 1;
      if (startCode <= endCode) {
        for (let c = startCode; c <= endCode && vals.length < 52; c += step) {
          vals.push(String.fromCharCode(c));
        }
      } else {
        for (let c = startCode; c >= endCode && vals.length < 52; c -= step) {
          vals.push(String.fromCharCode(c));
        }
      }
    }
    bracketMatches.push({ matchStr, values: vals });
  }

  bracketMatches.forEach((bm) => {
    const token = `__BRACKET_${bracketIndex++}__`;
    templateWithTokens = templateWithTokens.replace(bm.matchStr, token);
    tokens.push(token);
    varValueSets.push(bm.values);
  });

  // 2. Replace each asterisk '*' sequentially
  let astIndex = 0;
  while (templateWithTokens.includes('*')) {
    const token = `__AST_${astIndex}__`;
    templateWithTokens = templateWithTokens.replace('*', token);
    tokens.push(token);

    const cfg = wildcardConfigs[astIndex] || DEFAULT_WILDCARD_CONFIG;

    const vals: string[] = [];
    if (cfg.seqType === 'numeric') {
      const fromStr = String(cfg.numFrom ?? '1').trim();
      const toStr = String(cfg.numTo ?? '10').trim();
      const from = parseInt(fromStr, 10) || 0;
      const to = parseInt(toStr, 10) || 0;
      const step = Math.max(1, Math.abs(cfg.numStep || 1));
      const padLen =
        fromStr.startsWith('0') && fromStr.length > 1
          ? fromStr.length
          : toStr.startsWith('0') && toStr.length > 1
          ? toStr.length
          : 0;

      if (from <= to) {
        for (let v = from; v <= to && vals.length < 1000; v += step) {
          vals.push(padLen > 0 ? String(v).padStart(padLen, '0') : String(v));
        }
      } else {
        for (let v = from; v >= to && vals.length < 1000; v -= step) {
          vals.push(padLen > 0 ? String(v).padStart(padLen, '0') : String(v));
        }
      }
    } else {
      const fromRaw = (cfg.alphaFrom || '').trim();
      const toRaw = (cfg.alphaTo || '').trim();
      const fromChar = fromRaw ? fromRaw[0] : 'a';
      const toChar = toRaw ? toRaw[0] : fromChar >= 'A' && fromChar <= 'Z' ? 'Z' : 'z';
      const startCode = fromChar.charCodeAt(0);
      const endCode = toChar.charCodeAt(0);
      const step = Math.max(1, Math.abs(cfg.alphaStep || 1));
      if (startCode <= endCode) {
        for (let c = startCode; c <= endCode && vals.length < 52; c += step) {
          vals.push(String.fromCharCode(c));
        }
      } else {
        for (let c = startCode; c >= endCode && vals.length < 52; c -= step) {
          vals.push(String.fromCharCode(c));
        }
      }
    }
    varValueSets.push(vals.length > 0 ? vals : ['']);
    astIndex++;
  }

  if (tokens.length === 0) {
    return [rawTemplate];
  }

  // 3. Compute Cartesian product across all tokens
  let combinations: string[] = [''];
  for (let i = 0; i < varValueSets.length; i++) {
    const nextCombos: string[] = [];
    const set = varValueSets[i];
    for (const combo of combinations) {
      for (const val of set) {
        nextCombos.push(combo ? `${combo}§§§${val}` : val);
        if (nextCombos.length >= 2000) break;
      }
      if (nextCombos.length >= 2000) break;
    }
    combinations = nextCombos;
  }

  // 4. Map combinations back into URLs
  return combinations.slice(0, 2000).map((comb) => {
    const parts = comb.split('§§§');
    let u = templateWithTokens;
    tokens.forEach((tok, idx) => {
      u = u.replace(tok, parts[idx] ?? '');
    });
    return u;
  });
};
